# Generated by Django 2.2.2 on 2019-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdaccount',
            name='memo',
            field=models.CharField(max_length=140, null=True, verbose_name='memo'),
        ),
    ]
